version: '2'
services:
  redis-master:
    image: 'bitnami/redis:latest'
    expose:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=password-master

  redis-replica:
    image: 'bitnami/redis:latest'
    expose:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=password-master
      - REDIS_PASSWORD=password-replica-1

  redis-replica1:
    image: 'bitnami/redis:latest'
    expose:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=password-master
      - REDIS_PASSWORD=password-replica-2
  
  redis-replica2:
    image: 'bitnami/redis:latest'
    expose:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=password-master
      - REDIS_PASSWORD=password-replica-3
  
  redis-replica3:
    image: 'bitnami/redis:latest'
    expose:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=password-master
      - REDIS_PASSWORD=password-replica-4

